name: CMake

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 0 1 */3 *" # trigger automatically every three months at 00:00

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup32
        uses: ilammy/msvc-dev-cmd@v1.9.0
        with:
          arch: x86

      - name: Build32
        run: |
          cmake -G "NMake Makefiles" -B ${{github.workspace}}\build\Bin32 -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL -D CMAKE_BUILD_TYPE=Release
          cd ${{github.workspace}}\build\Bin32\
          nmake
          mkdir ${{github.workspace}}\bin\Bin32\
          move "${{github.workspace}}\build\Bin32\*.exe" "${{github.workspace}}\bin\Bin32\"

      - name: Setup64
        uses: ilammy/msvc-dev-cmd@v1.9.0
        with:
          arch: x64

      - name: Build64
        run: |
          cmake -G "NMake Makefiles" -B ${{github.workspace}}\build\Bin64 -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL -D CMAKE_BUILD_TYPE=Release
          cd ${{github.workspace}}\build\Bin64\
          nmake
          mkdir ${{github.workspace}}\bin\Bin64\
          move "${{github.workspace}}\build\Bin64\*.exe" "${{github.workspace}}\bin\Bin64\"

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: c1-launcher-current-build-${{env.BRANCH_NAME}}
          path: ${{github.workspace}}\bin\*
